[package]
name = "signals"
version = "0.1.0"
authors = ["JoshuaBatty <joshpbatty@gmail.com>"]
edition = "2018"

[dependencies]
nannou = "0.12"
serde = "1"
sacn = "0.4.4"
ether-dream = "0.2.0"
nannou_laser = "0.3.0"
nannou_audio = "0.2.0"